[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']
workDir = '/app/backend'

[phases.install]
cmds = [
    'cd /app/backend',
    'npm ci',
    'npm run build'
]

[start]
cmd = 'cd /app/backend && npm start'

[variables]
NODE_ENV = 'production'
NPM_CONFIG_PRODUCTION = 'false'